### ISSUE TITLE
Trying to use with IBox2 controller

### ISSUE THREAD

**Issue by mora** [emc2cube/Milight-Controller#1]
Does anyone know why this doesn't work with the IBox2 controller and strip lights?  I had to modify the script to send byte data instead of String data in the UDPSock.sendto function so that python wouldn't complain.  Now when I send a command there's no response and the lights don't change...

**Comment by emc2cube** [comment]
Every bridge version use different commands, you may want to try the ones in https://community.smartthings.com/t/integration-of-milight-limitlessled-easybulb-etc-2-methods/31819/42
Or on any other recent home automation forums to try to find the ones the iBox2 uses.

Then you can modify these variables accordingly

```
## Commands & Groups
alloff = '\x41\x00\x55'     #Group ALL OFF
allon = '\x42\x00\x55'      #Group ALL 
```
