### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by NoCodeAvaible** [emc2cube/Milight-Controller#2]
Hey,
is there maybe any paper where I can read about groups because I don't understand the principe of them.
Thank's for every help in advance:)

**Comment by emc2cube** [comment]
Groups = Zones
http://mi-light.com/Home/MiLightWifiController
It just mirror the remote / app layout and usually you would set up your lights as 1 group/zone = 1 room or any specific group of lights you want to be able to control together with 1 button press.
